font:
    normal:
        family: Jetbrains Mono
        style: Regular
    size: 12
    offset:
        x: 0
        y: 1
background_opacity: 0.9
shell:
    program: /usr/bin/zsh
window:
    dimensions:
        columns: 120
        lines: 30
    padding:
        x: 10
        y: 10
