font:
    normal:
        family: Jetbrains Mono
        style: Regular
    size: 12
    offset:
        x: 0
        y: 1
background_opacity: 0.95
shell:
    program: /usr/bin/zsh
window:
    position:
        x: 200
        y: 100
    dimensions:
        columns: 120
        lines: 30
    padding:
        x: 10
        y: 10
key_bindings:
    - {key: V, mods: Control, action: Paste}
